version: '3'
services:
  db:
    image: postgres:latest
    container_name: taller_postgres
    environment:
      POSTGRES_DB: taller
      POSTGRES_USER: utn
      POSTGRES_PASSWORD: utn    
    ports:  
      - "5433:5432"
    volumes:
      - utn:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    depends_on:
      - db

volumes:
  utn:
